# Steps to enable this build are:
#
# Generate the OAUTH-TOKEN at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt VAR_NAME=[OAUTH-TOKEN] -r apereo/cas --add env.global
# Encrypted settings include SONATYPE_USER, SONATYPE_PWD, GH_TOKEN, COVERITY_SCAN_TOKEN, COVERALLS_REPO_TOKEN

language: java
sudo: true
dist: trusty
services:
  - docker
branches:
  only:
  - master
jdk:
- oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
git:
  depth: 1
notifications:
  slack: apereo:tUFPsW9tmnzVSADu1LqqSUV8
  # Webhook notification turned on for coveralls to support parallel build jobs
  webhooks:
    secure: "e3Lkn/iMpq9IjNrBQqMAKAxCbKUcd5t6zbow+l39a5n7trIUcBzgK9YXlSBigRyVnKXwNmI08WQN0GMJuWoT2u9cda5qttgZ5C8p/RFWxGKz6qhlmKwcwmipasU0ykvMARB6nrTMwMeMV/O5btt2xko8KfsRQdmqyZGJBglhDsc="
matrix:
  fast_finish: true
env:
  global:
  - JAVA_OPTS="-Xms512m -Xmx3048m -Xss128m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -Xverify:none -server"
  - SPRING_MAIN_BANNER-MODE="off"
  - COVERALLS_PARALLEL=true
  - secure: "ScUSTo0if5m7ddnwUA7EaYucc6yzEUrKLk0DzCvkMfjn2h5taUFSKHx+S0hd2EzJofv+Em4eI5qncSK5LTxgD7HhHR1e3iZp+SqJenhhOnbuciZfg4QA+tUGw3XUdmREac5cz2l0qhi1q4vsnnZARj2d4vvf2HWuNtEOBu/ZAKI="
  - secure: "iWPPLKSS3zBs2adqLPkMiHfCj2hSLyD5BoV3oodhR7Ne83Kpn1khRcEWFoHF3Ed11eSU+glNdPSzUpc8TzwTZGx5B3RU2Qp36hZFyjuzNWJARmoVPYMiEg3FFBQrUR75w+Tbtn6zPkiAk6nl0K5ewmY0/xixVdnTLXL5HjpE2rc="
  - secure: "f3mDIZ8m6NYJXI8KvWD/sZRSeCCyIyfgPRy3Q6o9u9WyHZuYaJf95Ia0eJQ3gxUDS1TKL31Vk08dhFKrfIcKgifFPa2uQ2uyJkvGxlarMTQ+tpqsZYp4zAJgKc9r4xdZasvF2k4xqr+pl9AFjlpXB4jDD59XPXt3DcRABOYA9sM="
  - secure: "A0B1HJoHzvYGT4pPWPW1bQDS3Ne755vZ/VZ20OtVRgJHTTQfK13eKgH0VbYpEyZKJAFIexmaDVQ0XUdNukzrAoI6rKSm5vwam6qjELrvrKH2ovMgd1xvS2a5a1no5OT3QP3TXKKlmOTdS+Q5ZspjslBxpay3q7aKA9GMNvzChko="
  matrix:
  - MATRIX_JOB_TYPE=BUILD
  - MATRIX_JOB_TYPE=SNAPSHOT
  - MATRIX_JOB_TYPE=STYLE
  - MATRIX_JOB_TYPE=JAVADOC
  - MATRIX_JOB_TYPE=CFGMETADATA
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=NONE
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=CASSANDRA
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=DYNAMODB
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=COSMOSDB
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=COUCHBASE
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=FILESYSTEM
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=IGNITE
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=INFLUXDB
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=LDAP
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=MAIL
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=MEMCACHED
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=MONGODB
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=REDIS
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=COUCHDB
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=MSSQLSERVER
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=MYSQL
  - MATRIX_JOB_TYPE=TEST MATRIX_SERVER=POSTGRES
  - MATRIX_JOB_TYPE=DEPUPDATE
  - MATRIX_JOB_TYPE=DEPANALYZE
before_install:
- unset _JAVA_OPTIONS
- chmod -R 777 ./ci/*.sh
- ./ci/push-docs-ghpages.sh
- ./ci/init-travis-build.sh
install:
- ./ci/install.sh
script:
- ./ci/script.sh
after_script:
- ./ci/stop.sh


